table DimGraphNode

	column graph_node_key
		dataType: string
		isHidden
		summarizeBy: none
		sourceColumn: graph_node_key

		annotation SummarizationSetBy = Automatic

	column node_type
		dataType: string
		summarizeBy: none
		sourceColumn: node_type

		annotation SummarizationSetBy = Automatic

	column node_label
		dataType: string
		summarizeBy: none
		sourceColumn: node_label

		annotation SummarizationSetBy = Automatic

	column node_subtype
		dataType: string
		summarizeBy: none
		sourceColumn: node_subtype

		annotation SummarizationSetBy = Automatic

	column location_id
		dataType: string
		isHidden
		summarizeBy: none
		sourceColumn: location_id

		annotation SummarizationSetBy = Automatic

	column area_key
		dataType: string
		isHidden
		summarizeBy: none
		sourceColumn: area_key

		annotation SummarizationSetBy = Automatic

	column sit_key
		dataType: string
		isHidden
		summarizeBy: none
		sourceColumn: sit_key

		annotation SummarizationSetBy = Automatic

	column user_id
		dataType: string
		isHidden
		summarizeBy: none
		sourceColumn: user_id

		annotation SummarizationSetBy = Automatic

	column graph_cluster_key
		dataType: string
		isHidden
		summarizeBy: none
		sourceColumn: graph_cluster_key

		annotation SummarizationSetBy = Automatic

	column workload
		dataType: string
		summarizeBy: none
		sourceColumn: workload

		annotation SummarizationSetBy = Automatic

	column location_name
		dataType: string
		summarizeBy: none
		sourceColumn: location_name

		annotation SummarizationSetBy = Automatic

	column folder_path
		dataType: string
		summarizeBy: none
		sourceColumn: folder_path

		annotation SummarizationSetBy = Automatic

	column risk_pressure
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: risk_pressure

		annotation SummarizationSetBy = Automatic

	column files_with_sit
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: files_with_sit

		annotation SummarizationSetBy = Automatic

	column file_sit_pair_count
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: file_sit_pair_count

		annotation SummarizationSetBy = Automatic

	column distinct_sit_count
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: distinct_sit_count

		annotation SummarizationSetBy = Automatic

	column high_confidence_match_count
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: high_confidence_match_count

		annotation SummarizationSetBy = Automatic

	column node_size
		dataType: double
		summarizeBy: none
		sourceColumn: node_size

		annotation SummarizationSetBy = Automatic

	column layout_x
		dataType: double
		summarizeBy: none
		sourceColumn: layout_x

		annotation SummarizationSetBy = Automatic

	column layout_y
		dataType: double
		summarizeBy: none
		sourceColumn: layout_y

		annotation SummarizationSetBy = Automatic

	column is_high_value
		dataType: boolean
		summarizeBy: none
		sourceColumn: is_high_value

		annotation SummarizationSetBy = Automatic

	column node_note
		dataType: string
		summarizeBy: none
		sourceColumn: node_note

		annotation SummarizationSetBy = Automatic

	partition DimGraphNode = m
		mode: import
		source =
				let
				    Source = Parquet.Document(File.Contents(ParquetRoot & "\dim_graph_node.parquet")),
				    Columns = Table.SelectColumns(Source, {"graph_node_key", "node_type", "node_label", "node_subtype", "location_id", "area_key", "sit_key", "user_id", "graph_cluster_key", "workload", "location_name", "folder_path", "risk_pressure", "files_with_sit", "file_sit_pair_count", "distinct_sit_count", "high_confidence_match_count", "node_size", "layout_x", "layout_y", "is_high_value", "node_note"}, MissingField.UseNull),
				    #"Changed Type" = Table.TransformColumnTypes(Columns, {{"graph_node_key", type text}, {"node_type", type text}, {"node_label", type text}, {"node_subtype", type text}, {"location_id", type text}, {"area_key", type text}, {"sit_key", type text}, {"user_id", type text}, {"graph_cluster_key", type text}, {"workload", type text}, {"location_name", type text}, {"folder_path", type text}, {"risk_pressure", Int64.Type}, {"files_with_sit", Int64.Type}, {"file_sit_pair_count", Int64.Type}, {"distinct_sit_count", Int64.Type}, {"high_confidence_match_count", Int64.Type}, {"node_size", type number}, {"layout_x", type number}, {"layout_y", type number}, {"is_high_value", type logical}, {"node_note", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table
