table DimGraphCluster

	column graph_cluster_key
		dataType: string
		isHidden
		summarizeBy: none
		sourceColumn: graph_cluster_key

		annotation SummarizationSetBy = Automatic

	column cluster_label
		dataType: string
		summarizeBy: none
		sourceColumn: cluster_label

		annotation SummarizationSetBy = Automatic

	column workload
		dataType: string
		summarizeBy: none
		sourceColumn: workload

		annotation SummarizationSetBy = Automatic

	column location_id
		dataType: string
		isHidden
		summarizeBy: none
		sourceColumn: location_id

		annotation SummarizationSetBy = Automatic

	column location_name
		dataType: string
		summarizeBy: none
		sourceColumn: location_name

		annotation SummarizationSetBy = Automatic

	column area_level_1
		dataType: string
		summarizeBy: none
		sourceColumn: area_level_1

		annotation SummarizationSetBy = Automatic

	column area_count
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: area_count

		annotation SummarizationSetBy = Automatic

	column files_with_sit
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: files_with_sit

		annotation SummarizationSetBy = Automatic

	column file_sit_pair_count
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: file_sit_pair_count

		annotation SummarizationSetBy = Automatic

	column distinct_sit_count
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: distinct_sit_count

		annotation SummarizationSetBy = Automatic

	column risk_pressure
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: risk_pressure

		annotation SummarizationSetBy = Automatic

	column risk_density
		dataType: double
		summarizeBy: none
		sourceColumn: risk_density

		annotation SummarizationSetBy = Automatic

	column high_confidence_match_count
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: high_confidence_match_count

		annotation SummarizationSetBy = Automatic

	column label_coverage_pct
		dataType: double
		summarizeBy: none
		sourceColumn: label_coverage_pct

		annotation SummarizationSetBy = Automatic

	column cluster_rank
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: cluster_rank

		annotation SummarizationSetBy = Automatic

	column layout_x
		dataType: double
		summarizeBy: none
		sourceColumn: layout_x

		annotation SummarizationSetBy = Automatic

	column layout_y
		dataType: double
		summarizeBy: none
		sourceColumn: layout_y

		annotation SummarizationSetBy = Automatic

	column node_size
		dataType: double
		summarizeBy: none
		sourceColumn: node_size

		annotation SummarizationSetBy = Automatic

	partition DimGraphCluster = m
		mode: import
		source =
				let
				    Source = Parquet.Document(File.Contents(ParquetRoot & "\dim_graph_cluster.parquet")),
				    Columns = Table.SelectColumns(Source, {"graph_cluster_key", "cluster_label", "workload", "location_id", "location_name", "area_level_1", "area_count", "files_with_sit", "file_sit_pair_count", "distinct_sit_count", "risk_pressure", "risk_density", "high_confidence_match_count", "label_coverage_pct", "cluster_rank", "layout_x", "layout_y", "node_size"}, MissingField.UseNull),
				    #"Changed Type" = Table.TransformColumnTypes(Columns, {{"graph_cluster_key", type text}, {"cluster_label", type text}, {"workload", type text}, {"location_id", type text}, {"location_name", type text}, {"area_level_1", type text}, {"area_count", Int64.Type}, {"files_with_sit", Int64.Type}, {"file_sit_pair_count", Int64.Type}, {"distinct_sit_count", Int64.Type}, {"risk_pressure", Int64.Type}, {"risk_density", type number}, {"high_confidence_match_count", Int64.Type}, {"label_coverage_pct", type number}, {"cluster_rank", Int64.Type}, {"layout_x", type number}, {"layout_y", type number}, {"node_size", type number}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table
