table FactGraphEdge

	column edge_key
		dataType: string
		isHidden
		summarizeBy: none
		sourceColumn: edge_key

		annotation SummarizationSetBy = Automatic

	column source_node_key
		dataType: string
		isHidden
		summarizeBy: none
		sourceColumn: source_node_key

		annotation SummarizationSetBy = Automatic

	column target_node_key
		dataType: string
		isHidden
		summarizeBy: none
		sourceColumn: target_node_key

		annotation SummarizationSetBy = Automatic

	column source_node_type
		dataType: string
		summarizeBy: none
		sourceColumn: source_node_type

		annotation SummarizationSetBy = Automatic

	column target_node_type
		dataType: string
		summarizeBy: none
		sourceColumn: target_node_type

		annotation SummarizationSetBy = Automatic

	column source_node_label
		dataType: string
		summarizeBy: none
		sourceColumn: source_node_label

		annotation SummarizationSetBy = Automatic

	column target_node_label
		dataType: string
		summarizeBy: none
		sourceColumn: target_node_label

		annotation SummarizationSetBy = Automatic

	column edge_type
		dataType: string
		summarizeBy: none
		sourceColumn: edge_type

		annotation SummarizationSetBy = Automatic

	column edge_label
		dataType: string
		summarizeBy: none
		sourceColumn: edge_label

		annotation SummarizationSetBy = Automatic

	column graph_cluster_key
		dataType: string
		isHidden
		summarizeBy: none
		sourceColumn: graph_cluster_key

		annotation SummarizationSetBy = Automatic

	column file_count
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: file_count

		annotation SummarizationSetBy = Automatic

	column file_sit_pair_count
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: file_sit_pair_count

		annotation SummarizationSetBy = Automatic

	column distinct_sit_count
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: distinct_sit_count

		annotation SummarizationSetBy = Automatic

	column risk_pressure
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: risk_pressure

		annotation SummarizationSetBy = Automatic

	column high_confidence_match_count
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: high_confidence_match_count

		annotation SummarizationSetBy = Automatic

	column total_match_count
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: total_match_count

		annotation SummarizationSetBy = Automatic

	column edge_weight
		dataType: double
		summarizeBy: none
		sourceColumn: edge_weight

		annotation SummarizationSetBy = Automatic

	partition FactGraphEdge = m
		mode: import
		source =
				let
				    Source = Parquet.Document(File.Contents(ParquetRoot & "\fact_graph_edge.parquet")),
				    Columns = Table.SelectColumns(Source, {"edge_key", "source_node_key", "target_node_key", "source_node_type", "target_node_type", "source_node_label", "target_node_label", "edge_type", "edge_label", "graph_cluster_key", "file_count", "file_sit_pair_count", "distinct_sit_count", "risk_pressure", "high_confidence_match_count", "total_match_count", "edge_weight"}, MissingField.UseNull),
				    #"Changed Type" = Table.TransformColumnTypes(Columns, {{"edge_key", type text}, {"source_node_key", type text}, {"target_node_key", type text}, {"source_node_type", type text}, {"target_node_type", type text}, {"source_node_label", type text}, {"target_node_label", type text}, {"edge_type", type text}, {"edge_label", type text}, {"graph_cluster_key", type text}, {"file_count", Int64.Type}, {"file_sit_pair_count", Int64.Type}, {"distinct_sit_count", Int64.Type}, {"risk_pressure", Int64.Type}, {"high_confidence_match_count", Int64.Type}, {"total_match_count", Int64.Type}, {"edge_weight", type number}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table
