table FactFileSITTag

	column hit_id
		dataType: string
		isHidden
		summarizeBy: none
		sourceColumn: hit_id

		annotation SummarizationSetBy = Automatic

	column file_id
		dataType: string
		isHidden
		summarizeBy: none
		sourceColumn: file_id

		annotation SummarizationSetBy = Automatic

	column leaf_area_key
		dataType: string
		isHidden
		summarizeBy: none
		sourceColumn: leaf_area_key

		annotation SummarizationSetBy = Automatic

	column location_id
		dataType: string
		isHidden
		summarizeBy: none
		sourceColumn: location_id

		annotation SummarizationSetBy = Automatic

	column tag_type
		dataType: string
		summarizeBy: none
		sourceColumn: tag_type

		annotation SummarizationSetBy = Automatic

	column sit_key
		dataType: string
		isHidden
		summarizeBy: none
		sourceColumn: sit_key

		annotation SummarizationSetBy = Automatic

	column sit_name
		dataType: string
		summarizeBy: none
		sourceColumn: sit_name

		annotation SummarizationSetBy = Automatic

	column workload
		dataType: string
		summarizeBy: none
		sourceColumn: workload

		annotation SummarizationSetBy = Automatic

	column workload_code
		dataType: string
		summarizeBy: none
		sourceColumn: workload_code

		annotation SummarizationSetBy = Automatic

	column last_modified_date
		dataType: dateTime
		formatString: Short Date
		summarizeBy: none
		sourceColumn: last_modified_date

		annotation UnderlyingDateTimeDataType = Date

		annotation SummarizationSetBy = Automatic

	column tag_low_confidence_count
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: tag_low_confidence_count

		annotation SummarizationSetBy = Automatic

	column tag_medium_confidence_count
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: tag_medium_confidence_count

		annotation SummarizationSetBy = Automatic

	column tag_high_confidence_count
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: tag_high_confidence_count

		annotation SummarizationSetBy = Automatic

	column tag_total_count
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: tag_total_count

		annotation SummarizationSetBy = Automatic

	column has_tag_confidence
		dataType: boolean
		summarizeBy: none
		sourceColumn: has_tag_confidence

		annotation SummarizationSetBy = Automatic

	column observed_count
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: observed_count

		annotation SummarizationSetBy = Automatic

	column sensitivity_label
		dataType: string
		summarizeBy: none
		sourceColumn: sensitivity_label

		annotation SummarizationSetBy = Automatic

	column retention_label
		dataType: string
		summarizeBy: none
		sourceColumn: retention_label

		annotation SummarizationSetBy = Automatic

	partition FactFileSITTag = m
		mode: import
		source =
				let
				    Source = Parquet.Document(File.Contents(ParquetRoot & "\fact_file_sit_tag.parquet")),
				    Columns = Table.SelectColumns(Source, {"hit_id", "file_id", "leaf_area_key", "location_id", "tag_type", "sit_key", "sit_name", "workload", "workload_code", "last_modified_date", "tag_low_confidence_count", "tag_medium_confidence_count", "tag_high_confidence_count", "tag_total_count", "has_tag_confidence", "observed_count", "sensitivity_label", "retention_label"}, MissingField.UseNull),
				    #"Changed Type" = Table.TransformColumnTypes(Columns, {{"hit_id", type text}, {"file_id", type text}, {"leaf_area_key", type text}, {"location_id", type text}, {"tag_type", type text}, {"sit_key", type text}, {"sit_name", type text}, {"workload", type text}, {"workload_code", type text}, {"last_modified_date", type date}, {"tag_low_confidence_count", Int64.Type}, {"tag_medium_confidence_count", Int64.Type}, {"tag_high_confidence_count", Int64.Type}, {"tag_total_count", Int64.Type}, {"has_tag_confidence", type logical}, {"observed_count", Int64.Type}, {"sensitivity_label", type text}, {"retention_label", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table
